# Copyright (C) 2025-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
- name: Common tasks for every playbooks
  import_playbook: boilerplate.yml

- name: Gather facts
  import_playbook: facts.yml

- name: Reset cluster
  hosts: etcd:k8s_cluster:calico_rr
  gather_facts: False
  pre_tasks:
    - name: Reset Confirmation
      set_fact:
        reset_confirmation_prompt:
          user_input: "yes"
      run_once: True
      when:
        - not (skip_confirmation | default(false) | bool)
        - not (reset_confirmation is defined and reset_confirmation.user_input == "yes")

    - name: Check confirmation
      fail:
        msg: "Reset confirmation failed"
      when:
        - not reset_confirmation | default(false) | bool
        - not reset_confirmation_prompt.user_input | default("") == "yes"

    - name: Gather information about installed services
      service_facts:

  environment: "{{ proxy_disable_env | default(env_proxy | default({})) }}"
  roles:
    - { role: kubespray-defaults }
    - {
        role: kubernetes/preinstall,
        when: "dns_mode != 'none' and resolvconf_mode == 'host_resolvconf'",
        tags: resolvconf,
        dns_early: true,
      }
    - { role: reset, tags: reset }

- name: Cleanup PVC directories
  hosts: "{{ inference_delegate | default('kube_control_plane') }}"
  gather_facts: False
  tags: always
  tasks:
    - name: Find PVC directories on remote host
      find:
        paths: "{{ pvc_base_path | default('/opt/local-path-provisioner') }}"
        patterns: "pvc*"
        file_type: any
      register: pvc_dirs
      tags: always

    - name: Show PVC directories to be deleted
      debug:
        var: pvc_dirs.files
      tags: always

    - name: Cleanup PVC
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ pvc_dirs.files }}"
      failed_when: false
      tags: always
