# Copyright (C) 2025-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: peer-auth-ingress
  namespace: ingress-nginx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
  mtls:
    mode: STRICT
  portLevelMtls:
    443:
      mode: PERMISSIVE
    8443:
      mode: PERMISSIVE
