# Copyright (C) 2025-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ include "ovms-model-server.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ovms-model-server.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.modelSource }}
  ports:
  # gRPC port
  - name: grpc
    port: {{ .Values.service.grpcPort }}
    targetPort: {{ .Values.server.grpcPort }}
    protocol: TCP
  # REST API port
  - name: rest
    port: {{ .Values.service.restPort }}
    targetPort: {{ .Values.server.restPort }}
    protocol: TCP
  {{- end }}
  selector:
    {{- include "ovms-model-server.selectorLabels" . | nindent 4 }}
